version: "3.8"
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    volumes:
      - E:/learning/postgresql/todo/client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
